name: mylamp_flutter_v4_stable
description: A MYLamp Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_platform_widgets: ^0.60.2
  http: ^0.12.0
  flutter_flavor: ^1.0.1+1
  flutter_bloc: ^6.0.5
  equatable: ^1.1.1
  shared_preferences: ^0.5.10
  fluid_bottom_nav_bar: ^1.1.1
  fluttertoast: ^7.1.1
#  flutter_blue: ^0.7.2
  flutter_time_picker_spinner: ^1.0.6+1
  intl: ^0.16.1
  flutter_map: ^0.10.1+1
  image_picker: ^0.6.7+12
  dio: 3.0.10
  progress_dialog: ^1.2.4
  photo_view: ^0.10.2
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  get: ^3.13.2
  flutter_bluetooth_serial: ^0.2.2
  scoped_model: ^1.0.1
  geolocator: ^6.1.9
  toggle_switch: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/